module.exports = {
	en: {
		message: {
			hello: 'Hi, there. ASD',
			site_small_text: 'ASD',
			site_big_text: 'ASD',
			toggle_navigation: 'Toggle navigation',
			message_count: 'You have {count} messages',
			notiification_count: 'You have {count} notifications',
			task_count: 'You have {count} tasks',
			view_all: 'View All',
			login_form_title: 'Login',
			email_field: 'Email',
			password_field: 'Password',
			submit_btn: 'Submit',
			cancel_btn: 'Cancel',
			invalid_email: 'Invalid Email',
			invalid_password: 'Invalid Password',
			fix_error_first: 'Please fix the errors',
			error: 'Oops!',
			success: 'Success',
			warning: 'Warning',
			info: 'Info',
			login_succeeded: 'Login succeeded',
			login_failed: 'Login failed',
			logout_succeeded: 'Logout succeeded',
			user_invalid: 'Invalid user',
			dashboard: 'Dashboard',
			article_list: 'Articles',
			category_list: 'Categories',
			user_list: 'Users',
			banner_list: 'Banners',
			page_view: 'Page View',
			menu: 'Menu',
			logout: 'Logout',
			article_editor: 'Article',
			banner_editor: 'Banner',
			user_editor: 'User',
			category_editor: 'Category',
			id: 'ID',
			title: 'Title',
			category: 'Category',
			author: 'Author',
			top: 'Top',
			online_time: 'Online Time',
			created: 'Created',
			modified: 'Modified',
			start_time: 'Start',
			end_time: 'End',
			actions: 'Actions',
			fast_links: 'Shortcuts',
			description: 'Description',
			isyoutube: 'Youtube',
			online: 'On',
			name: 'Name',
			display_name: 'Nickname',
			about_me: 'About Me',
			type: 'Type',
			sex: 'Gender',
			email: 'Email',
			parent: 'Parent',
			level: 'Level',

			add_article: 'Add Article',
			add_banner: 'Add Banner',
			add_category: 'Add Category',
			add_user: 'Add User',
			
			backend: {
				description: 'ASD is CMS'
			}
		}
	}
};