module.exports = {
	en: {
		message: {
			hello: 'Hi, there. ASD',
			site_small_text: 'ASD',
			site_big_text: 'ASD',
			toggle_navigation: 'Toggle navigation',
			message_count: 'You have {count} messages',
			notiification_count: 'You have {count} notifications',
			task_count: 'You have {count} tasks',
			view_all: 'View All',
			login_form_title: 'Login',
			email_field: 'Email',
			password_field: 'Password',
			title_field: 'Title',
			author_field: 'Author',
			category_field: 'Category',
			keyword_field: 'Keyword',
			approved_field: 'Approved',
			at_top_field: 'At Top',
			online_field: 'Online',
			youtube_field: 'Youtube',
			watermark_field: 'Watermark',
			description_field: 'Description',
			video_url_field: 'Video URL',
			url_field: 'URL',
			thumbnail_field: 'Thumbnail',
			name_field: 'Name',
			parent_field: 'Parent',
			password: 'Password',
			submit_btn: 'Submit',
			cancel_btn: 'Cancel',
			invalid_email: 'Invalid Email',
			invalid_password: 'Invalid Password',
			fix_error_first: 'Please fix the errors',
			error: 'Oops!',
			success: 'Success',
			warning: 'Warning',
			info: 'Info',
			login_succeeded: 'Login succeeded',
			login_failed: 'Login failed',
			logout_succeeded: 'Logout succeeded',
			user_invalid: 'Invalid user',
			dashboard: 'Dashboard',
			article_list: 'Articles',
			category_list: 'Categories',
			user_list: 'Users',
			banner_list: 'Banners',
			page_view: 'Page View',
			menu: 'Menu',
			logout: 'Logout',
			article_editor: 'Article',
			banner_editor: 'Banner',
			user_editor: 'User',
			category_editor: 'Category',
			id: 'ID',
			title: 'Title',
			category: 'Category',
			author: 'Author',
			top: 'Top',
			online_time: 'Online Time',
			created: 'Created',
			modified: 'Modified',
			start_time: 'Start',
			end_time: 'End',
			actions: 'Actions',
			fast_links: 'Shortcuts',
			description: 'Description',
			isyoutube: 'Youtube',
			online: 'On',
			name: 'Name',
			display_name: 'Display Name',
			about_me: 'About Me',
			type: 'Type',
			sex: 'Gender',
			email: 'Email',
			parent: 'Parent',
			level: 'Level',
			others: 'Others',
			acdc: 'AC/DC',
			male: 'Male',
			female: 'Female',
			sex: 'Sex',
			usual: 'Usual',
			admin: 'Admin',

			add_article: 'Add Article',
			add_banner: 'Add Banner',
			add_category: 'Add Category',
			add_user: 'Add User',

			select_author: 'Select author',
			select_category: 'Select category',
			please_select_category: 'Please select category',
			please_select_user: 'Please select author',
			please_fill_title: 'Please fill title',
			please_write_something: 'Please write something',
			please_fill_description: 'Please fill description',
			please_fill_url: 'Please fill URL',
			please_fill_email: 'Please fill valid Email',
			please_fill_username: 'Please fill username',
			please_fill_name: 'Please fill name',
			article_saved: 'Article saved',
			banner_saved: 'Banner saved',
			user_saved: 'User saved',
			category_saved: 'Category saved',
			unable_to_save: 'Unable to save',
			are_you_sure: 'Are you sure?',
			record_deleted: 'Record deleted',
			upload_thumbnail: 'Upload Thumbnail',
			unable_to_fetch_statistics: 'Unable to read the statistics',

			save: 'Save',
			close: 'Close',

			thumbnail: 'Thumbnail',
			panorama: 'Panorama',
			marcomarco: 'Marco/Marco',
			marco_left: 'Marco Left',
			marco_right: 'Marco Right',
			please_select_image: 'Please select 1 image',
			please_select_2_images: 'Please select 2 images',
			marco_image_dimension_dismatch: 'Marco/Marco images do not have same sizes, please upload again',
			
			backend: {
				description: 'ASD is CMS'
			}
		}//eo message
	},//eo en

	zhTW: {
		message: {
			hello: '你好',
			site_small_text: 'LC',
			site_big_text: 'LianCar 鏈車網',
			toggle_navigation: '展開',
			message_count: '你有 {count} 則訊息',
			notiification_count: '你有 {count} 通知',
			task_count: '你有 {count} 任務',
			view_all: '檢視全部',
			login_form_title: '登入',
			email_field: 'Email',
			password_field: '密碼',
			title_field: '標題',
			author_field: '作者',
			category_field: '分類',
			keyword_field: '關鍵字',
			approved_field: '核准',
			at_top_field: '置頂',
			online_field: '上線',
			youtube_field: 'Youtube',
			watermark_field: '浮水印',
			description_field: '描述',
			video_url_field: '影片URL',
			url_field: 'URL',
			thumbnail_field: '縮圖',
			name_field: '名稱',
			parent_field: '父類別',
			password: '密碼',
			submit_btn: '送出',
			cancel_btn: '取消',
			invalid_email: '無效的 Email',
			invalid_password: '無效的 Password',
			fix_error_first: '請修正錯誤',
			error: '糟了糕!',
			success: '成功',
			warning: '警告',
			info: '訊息',
			login_succeeded: '登入成功',
			login_failed: '登入失敗',
			logout_succeeded: '登出成功',
			user_invalid: '無效帳號',
			dashboard: '主控台',
			article_list: '文章',
			category_list: '分類',
			user_list: '使用者',
			banner_list: '廣告',
			page_view: '點擊率',
			menu: '菜單',
			logout: '登出',
			article_editor: '文章',
			banner_editor: '廣告',
			user_editor: '使用者',
			category_editor: '分類',
			id: 'ID',
			title: '標題',
			category: '分類',
			author: '作者',
			top: '置頂',
			online_time: '上線時間',
			created: '建立時間',
			modified: '修改時間',
			start_time: '開始時間',
			end_time: '結束時間',
			actions: '動作',
			fast_links: '快捷列',
			description: '描述',
			isyoutube: 'Youtube',
			online: '上線',
			name: '名稱',
			display_name: '顯示名稱',
			about_me: '關於我',
			type: '種類',
			sex: '性別',
			email: 'Email',
			parent: '父類別',
			level: '層級',
			others: '其他',
			acdc: '不確定',
			male: '男人',
			female: '女人',
			sex: '性～別',
			usual: '一般',
			admin: '管理員',

			add_article: '新增文章',
			add_banner: '新增廣告',
			add_category: '新增分類',
			add_user: '新增使用者',

			select_author: '選擇作者',
			select_category: '選擇分類',
			please_select_category: '請選擇分類',
			please_select_user: '請選擇作者',
			please_fill_title: '請貼寫標題',
			please_write_something: '請寫一些東西',
			please_fill_description: '請寫描述',
			please_fill_url: '請填URL',
			please_fill_email: '請填寫有效的Email',
			please_fill_username: '請填寫帳號',
			please_fill_name: '請填寫名稱',
			article_saved: '文章已儲存',
			banner_saved: '廣告已儲存',
			user_saved: '使用者已儲存',
			category_saved: '分類已儲存',
			unable_to_save: '無法儲存',
			are_you_sure: '你確定要這樣做？',
			record_deleted: '紀錄已刪除',
			upload_thumbnail: '上傳縮圖',
			unable_to_fetch_statistics: '無法讀取統計數字',

			save: '儲存',
			close: '關閉',

			thumbnail: '縮圖',
			panorama: '全景圖',
			marcomarco: '馬可/可馬',
			marco_left: '馬可左手',
			marco_right: '馬可右手',
			please_select_image: '請選擇1張圖',
			please_select_2_images: '請選擇2張圖',
			marco_image_dimension_dismatch: 'Marco哥對你上傳的圖不滿意，請確定左右手的圖一樣大',
			
			backend: {
				description: 'Aitch寫的後台'
			}
		}//eo message
	}//eo zhTW
};