CREATE TABLE IF NOT EXISTS `users` (
	`id`           SERIAL,
	`name`         VARCHAR(35) NOT NULL,
	`display_name` VARCHAR(35) NOT NULL,
	`email`        VARCHAR(40) NOT NULL,
	`password`     VARCHAR(40) NOT NULL,
	`about_me`     VARCHAR(255) DEFAULT "",
	`type`         ENUM('usual','admin') NOT NULL DEFAULT "usual",
	`sex`          ENUM('male','female','unknown') NOT NULL DEFAULT "unknown",
	`valid`        BOOL NOT NULL DEFAULT 1,
	`created`      DATETIME,
	`modified`     DATETIME,
	INDEX(`email`, `password`, `valid`),
	INDEX(`type`),
	INDEX(`name`, `email`, `password`),
	INDEX(`display_name`)
)ENGINE=MyISAM CHARSET utf8; 

CREATE TABLE IF NOT EXISTS `articles` (
  `id`              SERIAL,
  `category_id`     smallint(5) unsigned NOT NULL,
  `user_id`         bigint(20) unsigned NOT NULL,
  `type`            enum('usual','commercial','product') NOT NULL DEFAULT 'usual',
  `org_type`        enum('usual','commercial','product') NOT NULL,
  `position`        enum('top','middle','bottom') NOT NULL DEFAULT 'bottom',
  `position_weight` smallint(5) unsigned NOT NULL DEFAULT '0',
  `title`           varchar(250) NOT NULL,
  `abstract`        varchar(150) NOT NULL,
  `content`         longtext NOT NULL,
  `read_only`       tinyint(1) NOT NULL DEFAULT '0',
  `blocked`         tinyint(1) NOT NULL DEFAULT '0',
  `invalid`         tinyint(1) NOT NULL DEFAULT '0',
  `attached`        tinyint(1) NOT NULL DEFAULT '0',
  `thumbnail`       varchar(255) NOT NULL,
  `created_by`      enum('admin','usual') NOT NULL,
  `promoter_id`     bigint(20) unsigned DEFAULT NULL,
  `deleted`         tinyint(1) DEFAULT '0',
  `approved`        tinyint(1) NOT NULL DEFAULT '1',
  `paid`            tinyint(1) NOT NULL DEFAULT '0',
  `approved_time`   datetime DEFAULT NULL,
  `start_time`      datetime DEFAULT NULL,
  `at_top`          tinyint(1) NOT NULL DEFAULT '0',
  `global`          tinyint(1) NOT NULL DEFAULT '0',
  `is_target`       tinyint(1) NOT NULL DEFAULT '0',
  `count`           int(10) NOT NULL DEFAULT '0',
  `ntf_to_fb`       tinyint(1) NOT NULL DEFAULT '0',
  `keywords`        varchar(50) NOT NULL DEFAULT '',
  `display_type`    varchar(15) NOT NULL DEFAULT 'IMAGE',
  `video_url`       varchar(255) NOT NULL DEFAULT '',
  `created`         datetime NOT NULL,
  `modified`        datetime DEFAULT NULL,
  `valid`           tinyint(1) NOT NULL DEFAULT '1',
  INDEX(`user_id`),
  INDEX(`keywords`),
  INDEX(`start_time`),
  INDEX(`id`,`category_id`,`blocked`,`approved`),
  INDEX(`category_id`,`blocked`,`approved`),
  INDEX(`category_id`),
  INDEX(`id`,`category_id`),
  INDEX(`read_only`),
  INDEX(`type`),
  INDEX(`thumbnail`),
  INDEX(`attached`),
  INDEX(`blocked`),
  INDEX(`approved`),
  INDEX(`user_id`),
  FULLTEXT KEY `content` (`content`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Table for storing article records';

CREATE TABLE IF NOT EXISTS  `categories` (
  `id`          smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id`   smallint(5) unsigned DEFAULT NULL,
  `user_id`     bigint(20) unsigned NOT NULL COMMENT 'This fields refers to weee_admin_users'' `id`',
  `display`     tinyint(1) NOT NULL DEFAULT '1',
  `title`       varchar(30) NOT NULL,
  `level`       smallint(5) unsigned NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `for_admin`   tinyint(1) NOT NULL DEFAULT '0',
  `type`        enum('article','product') NOT NULL DEFAULT 'article',
  `count`       int(10) unsigned NOT NULL DEFAULT '0',
  `total_count` int(10) unsigned NOT NULL DEFAULT '0',
  `position`    varchar(20) NOT NULL DEFAULT '0',
  `created`     datetime NOT NULL,
  `modified`    datetime DEFAULT NULL,
  `valid`       tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY       KEY (`id`),
  KEY           `fk_category_to_admin_user` (`user_id`),
  INDEX(`id`,`position`),
  INDEX(`position`),
  INDEX(`parent_id`,`display`,`for_admin`),
  INDEX(`level`,`display`,`type`,`for_admin`),
  INDEX(`level`,`display`,`type`,`for_admin`,`position`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table for storing categories for article records. The catego';

CREATE TABLE IF NOT EXISTS `banners` (
  `id`          int(10) unsigned NOT NULL AUTO_INCREMENT,
  `description` varchar(100) NOT NULL,
  `img1`        varchar(155) NOT NULL,
  `img2`        varchar(155) DEFAULT NULL,
  `img3`        varchar(155) DEFAULT NULL,
  `img4`        varchar(155) DEFAULT NULL,
  `img5`        varchar(155) DEFAULT NULL,
  `img6`        varchar(155) DEFAULT NULL,
  `mimg`        varchar(155) DEFAULT NULL,
  `url`         varchar(155) NOT NULL,
  `display_old` tinyint(1) NOT NULL DEFAULT '0',
  `target`      enum('_self','_blank') NOT NULL DEFAULT '_blank',
  `online`      tinyint(1) NOT NULL,
  `start_time`  datetime NOT NULL,
  `end_time`    datetime NOT NULL,
  `type`        enum('huge','medium','small') NOT NULL DEFAULT 'medium',
  `position`    enum('1','2','3') NOT NULL DEFAULT '1',
  `is_youtube`  tinyint(1) DEFAULT '0',
  `creator_id`  bigint(20) unsigned NOT NULL,
  `created`     datetime NOT NULL,
  `modified`    datetime DEFAULT NULL,
  `valid`       tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY       KEY (`id`),
  KEY           `img1` (`img1`,`url`,`target`),
  KEY           `start_time` (`start_time`,`end_time`),
  KEY           `display_old` (`display_old`),
  KEY           `start_time_2` (`start_time`,`type`,`online`,`end_time`,`display_old`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `images` (
  `id`       bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name`     varchar(125) NOT NULL,
  `path`     varchar(255) NOT NULL,
  `ip`       varchar(45) NOT NULL,
  `size`     varchar(45) NOT NULL,
  `width`    varchar(5) NOT NULL,
  `height`   varchar(5) NOT NULL,
  `user_id`  bigint(20) unsigned NOT NULL DEFAULT '0',
  `model`    varchar(50) NOT NULL DEFAULT '',
  `model_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `created`  datetime NOT NULL,
  `modified` datetime NOT NULL,
  `valid`    tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY    KEY (`id`),
  UNIQUE     KEY `images_path` (`path`),
  KEY        `model_key` (`model`,`model_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `banner_displays` (
  `id`          bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `banner_id`   int(10) unsigned NOT NULL,
  `category_id` smallint(5) unsigned NOT NULL,
  `created`     datetime NOT NULL,
  `modified`    datetime DEFAULT NULL,
  UNIQUE        KEY `id` (`id`),
  KEY           `banner_id` (`banner_id`,`category_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;